mydjangoproject/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MainPage.as_view(), name='main'),
    path('login/', views.login, name='login'),
    path('about/', views.about, name='about'),
    path('addpage/', views.AddPage.as_view(), name='addpage'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', views.PostsCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.PostsTagPostList.as_view(), name='tag'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
    path('delete/<slug:slug>/', views.DeletePage.as_view(), name='delete_page'),
]

mydjangoproject/mydjangoproject/urls.py
from django.contrib import admin
from django.urls import path, include

from main_app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/posts/', PostsAPIList.as_view()),
    path('api/v1/posts/<int:pk>/', PostsAPIUpdate.as_view()),
    path('api/v1/postsdelete/<int:pk>/', PostsAPIDestroy.as_view()),
]

mydjangoproject/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html',
             email_template_name='users/password_reset_email.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy('users:password_reset_complete')
         ),
         name='password_reset_confirm'),
    path('password-change/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

mydjangoproject/main_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Posts(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, null=True)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)

    def __str__(self):
        return self.name

mydjangoproject/main_app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.utils.deconstruct import deconstructible

from .models import Category, ArticleAdditionalDescription, Posts


@deconstructible
class RussianValidator:
    ALLOWED_CHARS = 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя0123456789- '
    code = 'russian'

    def __init__(self, message=None):
        self.message = message if message else 'Должны присутствовать только русские символы, дефис и пробел.'

    def __call__(self, value, *args, **kwargs):
        if not (set(value) <= set(self.ALLOWED_CHARS)):
            raise ValidationError(self.message, code=self.code)


class AddPostForm(forms.ModelForm):
    cat = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Категория не выбрана', label='Категории')
    additional_info = forms.ModelChoiceField(queryset=ArticleAdditionalDescription.objects.all(),
                                             empty_label='Дополнительной информации нет', required=False,
                                             label='Доп информация')

    class Meta:
        model = Posts
        fields = ['title', 'slug', 'content', 'photo', 'is_published', 'cat', 'additional_info', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 50, 'rows': 5}),
        }
        labels = {'slug': 'URL'}

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 50:
            raise ValidationError('Длина превышает 50 символов')
        elif len(title) < 5:
            raise ValidationError('Длина заголовка меньше 5 символов')

        return title


class UploadFileForm(forms.Form):
    file = forms.ImageField(label='Файл')

mydjangoproject/main_app/views.py
from rest_framework import generics, viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAdminUser
from rest_framework.response import Response

from .models import Posts, Category
from .permissions import IsAdminOrReadOnly, IsOwnerOrReadOnly
from .serializers import PostsSerializer


class PostsAPIList(generics.ListCreateAPIView):
    queryset = Posts.objects.all()
    serializer_class = PostsSerializer
    permission_classes = (IsAuthenticatedOrReadOnly, )


class PostsAPIUpdate(generics.RetrieveUpdateAPIView):
    queryset = Posts.objects.all()
    serializer_class = PostsSerializer
    permission_classes = (IsOwnerOrReadOnly, )


class PostsAPIDestroy(generics.RetrieveDestroyAPIView):
    queryset = Posts.objects.all()
    serializer_class = PostsSerializer
    permission_classes = (IsAdminOrReadOnly, )

mydjangoproject/main_app/templates/main_app/about.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
{% for item in page_obj %}
<p>{{ item.pk }}: {{ item.title }}</p>
{% endfor %}

<nav>
    <ul>
        {% for p in page_obj.paginator.page_range %}
        <li>
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endfor %}
    </ul>
</nav>

{% endblock %}

mydjangoproject/main_app/templates/main_app/addpage.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p>
        <button type="submit">Отправить</button>
    </p>
</form>
{% endblock %}

mydjangoproject/main_app/templates/main_app/list_categories.html
{% for cat in cats %}
{% if cat.id == cat_selected %}
<li class="selected">{{cat.name}}</li>
{% else %}
<li><a href="{{ cat.get_absolute_url }}">{{cat.name}}</a></li>
{% endif %}
{% endfor %}

mydjangoproject/main_app/templates/main_app/list_tags.html
{% if tags %}
    <p>Теги:</p>
    <ul class="tags-list">
        {% for t in tags %}
        <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
        {% endfor %}
    </ul>
{% endif %}

mydjangoproject/main_app/templates/main_app/main.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-articles">
    {% for p in posts %}
    <li>
        <div class="article-panel">
            <p class="first">Категория: {{p.cat.name}} | Автор: {{ p.author.username|default:"неизвестен" }}</p>
            <p class="last">Дата: {{p.time_update|date:"d-m-Y H-i-s"}}</p>
        </div>
        {% if p.photo %}
        <p>
            <img class="img-article-left thumb" src="{{ p.photo.url }}">
        </p>
        {% endif %}
        <h2>{{p.title}}</h2>
        {% autoescape off %}
        {{p.content|linebreaks|truncatewords:40}}
        {% endautoescape %}
        <div class="clear"></div>
        <p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
    </li>
    {% endfor %}
</ul>
{% endblock %}

{% block navigation %}
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul>
        {% if page_obj.has_previous %}
        <li class="page-num">
            <a href="?page={{ page_obj.previous_page_number }}">&lt</a>
        </li>
        {% endif %}


        {% for p in paginator.page_range %}
        {% if page_obj.number == p %}
        <li class="page-num page-num-selected">{{ p }}</li>
        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-num">
            <a href="?page={{ page_obj.next_page_number }}">&gt</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}

mydjangoproject/main_app/templates/main_app/post.html
{% extends 'base.html' %}

{% block breadcrumbs %}
{% if perms.main_app.change_posts  %}
<p><a href="{% url 'edit_page' post.slug %}">Редактировать</a></p>
{% endif %}

<!-- Теги -->
{% with post.tags.all as tags %}
{% if tags %}
<ul class="tags-list">
    <li>Теги:</li>
    {% for t in tags %}
    <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}
{% endblock %}

{% block content %}
<h1>{{post.title}}</h1>

{% if post.photo %}
<p><img class="img-article-left" src="{{post.photo.url}}"></p>
{% endif %}

{{post.content|linebreaks}}
{% endblock %}

mydjangoproject/main_app/templates/main_app/posts_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Вы точно хотите удалить этот пост? "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Подтвердить">
</form>